[package]
name = "realworld-tide"
version = "0.1.0"
authors = ["colinbankier <colinbankier@gmail.com>"]
edition = "2018"

[[bin]]
name = "realworld-tide"
path = "src/main.rs"

[dependencies]
tide = { git = "https://github.com/rustasync/tide.git" }
diesel = { version = "1.4", features = ["postgres", "extras"] }
r2d2 = "0.8"
serde = "1.0"
serde_derive = "1.0"
serde_urlencoded = "0.5.4"
chrono = { version = "0.4.6", features = ["serde"] }
http = "0.1"
futures_01 = { version = "0.1.25", package = "futures" }
tokio-threadpool = "0.1.9"
log = "0.4.0"
env_logger = "0.6.0"
jsonwebtoken = "5.0.1"
config = "0.9.3"

[dependencies.futures-preview]
features = ["compat"]
version = "0.3.0-alpha.17"

[dev-dependencies]
fake = "1.2.2"
http-service = "0.3.1"
serde_json = "1.0"
